name: .NET 4.8

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Setup MSBuild.exe
        uses: warrenbuckley/Setup-MSBuild@v1

      - name: MSBuild
        working-directory: src
        run: msbuild MyProject.csproj
