name: .NET builder

on: [push]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Build DotNET
        run: |
           cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
           .\MSBuild.exe /p:Configuration=Release $Env:GITHUB_WORKSPACE
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: SSD-LED-AutoBuild
          path: SSD-LED\bin\Release
